### PR TITLE
Service secret optionally read from file

### PR DESCRIPTION
**Pull request by Ksisu**
Trusted services secret read from file when it is set.
It's useful for docker swarm secret feature.

### CODE REVIEW

**Comment by miklos-martin** [comment]
Hi @Ksisu, thanks for putting this together!

I think we should try the file IO only if the secret-file config is set. 

And I’m not sure about the fallback mechanism here. Wouldn’t you be surprised if you set a path with a typo, for example, but it wouldn’t tell you about it, just use the secret string from the config and would fail to authenticate otherwise valid signatures?

**Comment by Ksisu** [comment]
@miklos-martin you are absolutely right! I fixed those issues.
- read the file only if the `secret-file` is set
- when the `secret-file` is set but something went wrong it doesn't do any fallback

**Comment by miklos-martin** [comment]
Thanks!

**Comment by miklos-martin** [comment]
I've tagged a new minor version, it's on its wahy to maven central.
https://github.com/emartech/escher-akka-http/releases/tag/v1.1.0

**Pull request merged**
